### ISSUE TITLE
Breaks if second parameter is passed in

### ISSUE THREAD

**Issue by mgrigajtis** [jamesmartin/inline_svg#32] opened 2016-03-19 14:45 UTC
```
<%= inline_svg ("loader.svg", class: 'hidden') %>
```
Causes:
```
syntax error, unexpected ',', expecting ')'
...end=( inline_svg ("loader.svg", class: 'hidden') );@output_b...
...
```

**Comment by jamesmartin** [comment] 2016-04-12 01:31
@mgrigajtis try removing the space between the method name and the opening parentheses:

```
<%= inline_svg("loader.svg", class: 'hidden') %>
```

**Comment by jamesmartin** [comment] 2016-05-01 01:36
@mgrigajtis I'm closing this now to keep the issue tracker tidy. If your problem isn't solved, please mention me again and I'll reopen.

**Closed by jamesmartin** 2016-05-01 01:36 UTC

**Comment by ElliottRoche** [comment] 2017-07-27 19:46
@jamesmartin I'm having this issue as well. I don't have an extra space, and any option passed in that isn't the name of the svg causes nothing to render inside the element. I get an `<svg>` on the page but the only children that it ever contains are title, description, and metadata.

**Comment by jamesmartin** [comment] 2017-07-30 20:52
@ElliottRoche so we're clear, could you please paste the error message you're seeing, and the exact usage of the `inline_svg` method in your template.

**Comment by ElliottRoche** [comment] 2017-07-31 14:34
So this is a slim template and I've copied and pasted the code from the README and inserted my own SVG asset:
```
.ticker-container.flex.self-end
    = inline_svg("ticker.svg", id: 'some-id', class: 'some-class', data: {some: "value"}, size: '30% * 20%', title: 'Some Title', desc: 'Some description', nocomment: true, preserve_aspect_ratio: 'xMaxYMax meet', aria: true)
```

Here's what the output from the browser console looks like:
![2017-07-31 at 9 29 am](https://user-images.githubusercontent.com/3212954/28782538-0901bdf6-75d3-11e7-8b69-dbda6537935d.png)

If I remove the other parameters from the inline_svg call,
```
.ticker-container.flex.self-end
    = inline_svg("ticker.svg")
```
I get this output and the SVG renders correctly:
![2017-07-31 at 9 32 am](https://user-images.githubusercontent.com/3212954/28782633-55adb434-75d3-11e7-9c68-312b24b930cf.png)

**Comment by jamesmartin** [comment] 2017-08-01 00:34
@ElliottRoche I don't know much about what's happening inside Slim, but I suggest trying the [Output without HTML escaping directive](http://www.rubydoc.info/gems/slim/frames#Output_without_HTML_escaping___) as `inline_svg` already calls `html_safe` on the SVG string.

```slim
.ticker-container.flex.self-end
    == inline_svg("ticker.svg", id: 'some-id', class: 'some-class', data: {some: "value"}, size: '30% * 20%', title: 'Some Title', desc: 'Some description', nocomment: true, preserve_aspect_ratio: 'xMaxYMax meet', aria: true)
```

Otherwise, if you can reproduce this behavior in an ERB template then I'll take a closer look.
