### ISSUE TITLE
1.5.0 and 1.5.1 can no longer find assets in production

### ISSUE THREAD

**Issue by shepmaster** [jamesmartin/inline_svg#98] opened 2019-06-18 18:34 UTC
I am still debugging this, but I figured I'd open an issue earlier in case other people have the same problem.

We were previously using 1.4.0 with seemingly no issues, but on upgrading to 1.5.0 (or 1.5.1) we now get:

```html
<!-- SVG file not found: 'logo-black.svg' -->
```

The corresponding view is pretty basic:

```haml
= inline_svg "logo-black.svg", class: "welcome-logo"
```

What's extra strange is that this only appears when we've deployed to Heroku, not in local development.

---

> Which version of Rails are you using?

Ruby 2.6.2, Rails 5.2.3

> Are you using Webpack at all?

Yes, via webpacker

> Are you using Sprockets or Webpacker? Or both?

Both

> Are you using your own custom asset_finder?

No

> Could you paste your InlineSvg.configure block, if any

Not using one.

**Comment by shepmaster** [comment] 2019-06-18 19:32
Strangely, explicitly forcing the old asset finder *seems* to work (we are double checking):

```rb
Rails.application.config.after_initialize do |app|
  InlineSvg.configure do |config|
    config.asset_finder = app.instance_variable_get(:@assets)
  end
end
```

**Comment by jamesmartin** [comment] 2019-06-18 23:17
@shepmaster thanks for opening this issue and sorry about the problems you're having with 1.5x.

> Strangely, explicitly forcing the old asset finder _seems_ to work (we are double checking):

This is very strange because the Railtie should automatically configure that for you during App initialization. https://github.com/jamesmartin/inline_svg/blob/e32d1f68f904921c8e50e21edbc9cab7bacd7db6/lib/inline_svg/railtie.rb#L17-L20

I guess this must also mean that your app's assets are _not_ being precompiled by Heroku on deployment, which is the default behavior. If your assets _were_ being precompiled then there would be no Sprockets `@assets` instance variable and the gem would fallback to the `StaticAssetFinder`… 🤔

**Comment by beauraF** [comment] 2019-06-19 10:03
Hi @jamesmartin, I had the same problem when I went from `1.3.1` to `1.5.0` on _doctolib_.
I couldn't reproduce it locally. Only in production.

We use Sprockets and Webpack. But it is still Sprockets that manages the compilation of SVG. Of course we precompile our assets in production.

I'm trying to investigate. I'll come back to you if I have any further information.

**Comment by igorkasyanchuk** [comment] 2019-06-19 13:33
+1 for this issue. maybe because of this line: https://github.com/jamesmartin/inline_svg/compare/v1.5.0...v1.5.1#diff-f77654af79391ea695bddcf725119364R21

if you have webpacker it will use it for asset finder

**Comment by shepmaster** [comment] 2019-06-19 16:00
> This is very strange because the Railtie should automatically configure that for you during App initialization.

Exactly why I think it's so very strange!

> I guess this must also mean that your app's assets are _not_ being precompiled by Heroku on deployment, which is the default behavior. 

We certainly *intend* for the assets to be precompiled. The Heroku log states:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
```

> If your assets _were_ being precompiled then there would be no Sprockets `@assets` instance variable and the gem would fallback to the `StaticAssetFinder`

Wouldn't it fallback to the `Webpacker` loader, since we also have it?

https://github.com/jamesmartin/inline_svg/blob/e32d1f68f904921c8e50e21edbc9cab7bacd7db6/lib/inline_svg/railtie.rb#L17-L28

Said another way, why *wouldn't* `Webpacker` be available?

**Comment by shepmaster** [comment] 2019-06-19 16:15
Using this initialized also appears to work:

```rb
Rails.application.config.after_initialize do |app|
  InlineSvg.configure do |config|
    config.asset_finder = InlineSvg::StaticAssetFinder
  end
end
```

**Comment by shepmaster** [comment] 2019-06-19 16:18
And forcing the loader to be `WebpackAssetFinder` causes my development environment to exhibit the same problem as production, so this certainly seems like the right area to investigate.

```
config.asset_finder = InlineSvg::WebpackAssetFinder
```

**Comment by igorkasyanchuk** [comment] 2019-06-19 16:42
Ideal is to have both finders work together. Of course check if webpack if available, if not only static finder works

**Comment by shepmaster** [comment] 2019-06-19 18:42
> check if webpack if available

I think that may be a key problem for our case.

Our app uses *both* the asset pipeline and Webpack (via Webpacker) as we slowly migrate from the former to the latter. The two tools process completely independent sets of assets for us.

As I understand the problem, `app.instance_variable_get(:@assets)` returns `nil` in production because the assets have been precompiled. However, because we have Webpack, the `WebpackAssetFinder` is enabled. However, Webpack doesn't know about these assets, so when the SVG is requested the finder fails.

Prior to 1.5, the fallback would have gone to the static asset finder, which would find the precompiled assets .

**Comment by jamesmartin** [comment] 2019-06-19 22:02
@shepmaster thanks for clarifying that you're using both Sprockets _and_ Webpacker while you transition.

I added a note to the [readme](https://github.com/jamesmartin/inline_svg/blob/e32d1f68f904921c8e50e21edbc9cab7bacd7db6/README.md#sprockets-and-webpacker) when I released 1.5.0 that was intended to help with any confusion, but it was not clear enough:

> If you have both Sprockets and Webpacker enabled for some reason and you want Inline SVG to use Webpacker to find SVGs then you should configure the asset_finder appropriately

I'm going to add a note about using the `StaticAssetFinder` if you precompile assets in production.

In your case I think it's sufficient to just configure the `StaticAssetFinder` explicitly until you decide whether Webpacker will be bundling your image assets:

```ruby
InlineSvg.configure do |config|
  config.asset_finder = InlineSvg::StaticAssetFinder
end
```

Given this is a breaking change, I probably should have bumped the major version to 2.0. Apologies again for the disruption. 🤔 

> Ideal is to have both finders work together. Of course check if webpack if available, if not only static finder works

That's kind of a complicated problem because Webpacker doesn't expose any reliable method to ask, "is Webpacker bundling images". We *could* check the Webpacker manifest file and start greping for paths that appear to be images, but that's probably not very reliable.

**Comment by jamesmartin** [comment] 2019-06-19 22:33
I think I'm going to remove the auto-selection of Webpacker and make it "opt-in" for now. This is going to break too many Heroku Apps and it's not reasonable to make everybody do manual configuration to get back existing functionality.

**Comment by jamesmartin** [comment] 2019-06-19 22:49
I've release [v1.5.2](https://github.com/jamesmartin/inline_svg/releases/tag/v1.5.2), which completely reverts the automatic Webpacker detection and makes Webpack "opt-in" by default, meaning that if you're using Sprockets to serve assets (either dynamically, or precompiled), there should be no additional configuration required.

Please update to this version and let me know if you have any problems. Sorry for all the trouble these last couple of releases have caused.

**Comment by shepmaster** [comment] 2019-06-20 02:23
> @shepmaster thanks for clarifying that you're using both Sprockets _and_ Webpacker while you transition.

Sorry, I thought I communicated that in the initial comment.

> I added a note to the [readme](https://github.com/jamesmartin/inline_svg/blob/e32d1f68f904921c8e50e21edbc9cab7bacd7db6/README.md#sprockets-and-webpacker)

Yep, but it wasn't part of the [release notes](https://github.com/jamesmartin/inline_svg/releases) or [changelog](https://github.com/jamesmartin/inline_svg/blob/master/CHANGELOG.md) that Dependabot provided for our upgrade.

> Webpacker doesn't expose any reliable method to ask, "is Webpacker bundling images"

And in our case, webpack *is* bundling some images, just not those that we are using inline_svg for. In webpack land, we are using `@svgr/webpack`.

> Sorry for all the trouble these last couple of releases have caused.

Not at all! Thank you for your time and maintenance of a useful library!

**Comment by jamesmartin** [comment] 2019-06-25 07:11
@shepmaster I'm going to close this out now. Thanks again for taking the time to open up an issue and describe the problems you faced.

**Closed by jamesmartin** 2019-06-25 07:11 UTC

**Comment by richjdsmith** [comment] 2019-06-26 07:26
Thought I would chime in and see if a bit of extra info could help. 

I am using Rails 6.0rc1 - Ruby 2.5.3 and inline_svg v1.5.2 and I am only using webpacker (no sprockets).

When I use the `InlineSvg::WebpackAssetFinder` config, that finder only appears to find files that are precompiled (that is, I run `$./bin/webpack` before I start my server. If I do that, the finder find's my files no problem. However, it does not appear to use any assets found via `webpack-dev-server` or update changes based on if I remove or add files to my images folder.

This is the finder that I was using before (1.3) the 1.5.2 update:

```ruby
class WebpackerAssetFinder
  class FoundAsset
    require 'open-uri'
    attr_reader :path

    def initialize(path)
      @path = path
    end

    def pathname
      if Webpacker.dev_server.running?
        begin
          asset = open(webpacker_dev_server_url)
          tempfile = Tempfile.new(path)
          tempfile.binmode
          tempfile.write(asset.read)
          tempfile.rewind
          tempfile
        rescue StandardError => e
          Rails.logger.error "Error creating tempfile: #{e}"
          raise
        end
      else
        Rails.application.root.join("public", path.gsub(/\A\//, ""))
      end
    end

    private

    def webpacker_dev_server_url
      "#{Webpacker.dev_server.protocol}://#{Webpacker.dev_server.host_with_port}#{path}"
    end
  end

  def find_asset(filename)
    if webpack_asset_path = Webpacker.manifest.lookup(filename)
      FoundAsset.new(webpack_asset_path)
    end
  end
end

# Override the Sprockets asset finder. This is my old homebrew method.
InlineSvg.configure do |config|
  config.asset_finder = WebpackerAssetFinder.new
end
```

and it still works fine with the 1.5.2 version plugin.

**Comment by jamesmartin** [comment] 2019-06-27 07:19
@richjdsmith thanks for the information. As this seems to be a problem with the interaction between inline_svg and the Webpacker dev server would you mind opening a separate issue for this? Also, if you're motivated to help work on merging your working asset finder with the current version, that would be much appreciated.

Thanks 🙏
