### ISSUE TITLE
Feature request: SVG scrubber which strip unnecessary attributes tags

### ISSUE THREAD

**Issue by neumayr** [jamesmartin/inline_svg#55] opened 2017-03-03 14:56 UTC
Hi @jamesmartin :wave:

Can I have your feedback on this idea?
Some icons we want to use within our app are not optimized for changing color etc.
Cause is, the `svg` element is for example messed up with `enable-background="new 0 0 50 50"`, `fill="#181818"`.  The `path` element with `style="text-indent:0;…"`, `color="…"`, `fill="…"`, `overflow="…"`, etc. attributes.

I was thinking to have a new kind of Transformation scrubber like the `NoComment` Transformation, which whitewash/strips all the unnecessary attributes from the `svg` and `path` elements.

Expected Examples:

##### Original svg

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" enable-background="new 0 0 50 50" fill="#181818">
  <path style="text-indent:0;text-align:start;line-height:normal;text-transform:none;block-progression:tb;-inkscape-font-specification:Bitstream Vera Sans" d="M 25 3 C 12.86158 3 3 12.86158 3 25 C 3 37.13842 12.86158 47 25 47 C 37.13842 47 47 37.13842 47 25 C 47 12.86158 37.13842 3 25 3 z M 25 5 C 36.05754 5 45 13.94246 45 25 C 45 36.05754 36.05754 45 25 45 C 13.94246 45 5 36.05754 5 25 C 5 13.94246 13.94246 5 25 5 z M 34.0625 14.46875 L 23.125 31.46875 L 15.78125 24.84375 L 14.4375 26.34375 L 22.625 33.75 L 23.5 34.53125 L 24.125 33.53125 L 35.75 15.53125 L 34.0625 14.46875 z" color="#000" overflow="visible" enable-background="accumulate" font-family="Bitstream Vera Sans" fill="#181818"/>
</svg>
```

##### Simplified svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
  <path d="M 25 3 C 12.86158 3 3 12.86158 3 25 C 3 37.13842 12.86158 47 25 47 C 37.13842 47 47 37.13842 47 25 C 47 12.86158 37.13842 3 25 3 z M 25 5 C 36.05754 5 45 13.94246 45 25 C 45 36.05754 36.05754 45 25 45 C 13.94246 45 5 36.05754 5 25 C 5 13.94246 13.94246 5 25 5 z M 34.0625 14.46875 L 23.125 31.46875 L 15.78125 24.84375 L 14.4375 26.34375 L 22.625 33.75 L 23.5 34.53125 L 24.125 33.53125 L 35.75 15.53125 L 34.0625 14.46875 z" />
</svg>
```

What do you think about this idea, is this a possible feature you like to add to `inline_svg`?

**Comment by jamesmartin** [comment] 2017-03-05 23:34
@neumayr thanks for submitting this feature request. 

I want to think very carefully before adding new built-in transformations. I'm trying hard to prevent the core of this gem becoming complicated and difficult to maintain. If it's easy to maintain then I can keep it updated and compatible with a wide range of Rails projects. 

That said, I have a few questions about the functionality of this transformation:

- How do we know which attributes are unwanted? Would this be configurable by the user?
- How many built-in unwanted style attributes would we have to consider?
- Would it be possible for the user to configure the transformation to remove additional attributes?

One way to help me make a decision is to create a [Custom Transformation](https://github.com/jamesmartin/inline_svg#custom-transformations), demonstrating the intended behavior. If your custom transformation seems like it would be useful to many users then it would be an easier decision to accept it into the core.

If you're interested in writing a custom transformation then I'm happy to help you get it working. Check out the documentation and keep this issue updated with your progress.

**Comment by glebm** [comment] 2017-03-08 01:00
@neumayr Are you aware of https://github.com/svg/svgo? Performance-wise, it is perhaps best to run it on deployment on all svg files, or even before commiting the code.

Alternatively, if you really need to you can call it from Ruby via [execjs](https://github.com/rails/execjs).

**Comment by jamesmartin** [comment] 2017-03-27 01:04
Going to close this one out. @neumayr if you have further questions or need help with custom transforms, feel free to open another issue.

**Closed by jamesmartin** 2017-03-27 01:04 UTC
Labels: enhancement
